[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SimRop"
authors = [{name = "Flanders Make vzw", email = "info@flandersmake.be"}]
dynamic = ["version", "description"]
